services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=polling_system_db
      - DB_USER=postgres
      - DB_PASSWORD=@$#Utosh17
    networks:
      - backend_network
  db:
    image: postgres
    environment:
      - POSTGRES_DB=polling_system_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@$#Utosh17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
