# Generated by Django 5.1.4 on 2024-12-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_question_survey_choice_response_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_option',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
