# Generated by Django 5.1.4 on 2024-12-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_question_answer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
