# Generated by Django 5.1.4 on 2024-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_alter_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_option',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
